version: "3.7"

services:
  # Image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks: 
      - networks-app

  # Nginx
  nginx:
    container_name: app-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports: 
      - "91:80"
    volumes: 
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
    networks:
      - networks-app

  # MariaDB
  db:
    image: mariadb:10.3
    container_name: app-db
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker-compose/db/mysql:/var/lib/mysql/
      - ./.docker-compose/db/schemas:/docker-entrypoint-initdb.d/
    ports: 
      - "3308:3306"
    networks: 
      - networks-app

networks: 
  networks-app:
      driver: bridge