version: "3.7"

services:
  # Image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: app
    image: app-vue
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    command: ['yarn', 'serve']
    networks: 
      - networks-app

networks: 
  networks-app:
      driver: bridge